using FreshProduce.Application.Interfaces;
using FreshProduce.Domain.Entities;

namespace FreshProduce.Application.Services
{
    public class OrderService(IOrderRepository orderRepository, IRoundRepository roundRepository, IPricingService pricingService) : IOrderService
    {
        private readonly IOrderRepository _orderRepository = orderRepository;
        private readonly IRoundRepository _roundRepository = roundRepository;
        private readonly IPricingService _pricingService = pricingService;

        public async Task<Order> PlaceOrderAsync(
            string userId,
            Guid roundId,
            List<(Guid ProductId, decimal QuantityKg)> items,
            DeliveryType deliveryType,
            string? deliveryAddress = null,
            string? deliveryPhone = null,
            string? userName = null)
        {
            Round round = await GetValidRoundForOrdering(roundId);


            decimal fee = 0;
            if (deliveryType == DeliveryType.HomeDelivery)
            {
                fee = round.Neighborhood?.DeliveryFee ?? 20m;
            }

            Order order = CreateBaseOrder(userId, roundId, deliveryType, fee, deliveryAddress, deliveryPhone, userName);

            ProcessOrderItems(order, round, items);

            order.PrepaymentAmount = _pricingService.CalculatePrepaymentAmount(order.TotalEstimatedAmount);

            await UpdateRoundStatusIfTargetReached(round);

            await _orderRepository.AddAsync(order);
            // Note: Changes to round.RoundProducts and round.Status are already tracked by EF
            // They will be saved automatically when we save the order

            return order;
        }

        private async Task<Round> GetValidRoundForOrdering(Guid roundId)
        {
            Round round = await _roundRepository.GetByIdAsync(roundId);
            return round == null || round.Status != RoundStatus.Open
                ? throw new InvalidOperationException("Round is not open for orders.")
                : round;
        }

        private static Order CreateBaseOrder(
            string userId,
            Guid roundId,
            DeliveryType deliveryType,
            decimal deliveryFee,
            string? deliveryAddress,
            string? deliveryPhone,
            string? userName)
        {
            return new Order
            {
                Id = Guid.NewGuid(),
                OrderNumber = 0, // Will be auto-generated by database
                UserId = userId,
                UserName = userName,
                RoundId = roundId,
                Status = OrderStatus.Placed,
                OrderDate = DateTime.UtcNow,
                DeliveryType = deliveryType,
                DeliveryFee = deliveryFee,
                DeliveryAddress = deliveryAddress,
                DeliveryPhone = deliveryPhone
            };
        }

        private static void ProcessOrderItems(Order order, Round round, List<(Guid ProductId, decimal QuantityKg)> items)
        {
            decimal totalEstimated = 0;
            decimal totalTargetKg = round.RoundProducts.Sum(rp => rp.TargetQuantityKg);
            decimal transportShareEstimate = totalTargetKg > 0
                ? round.TotalTransportCost / totalTargetKg
                : 2.0m;

            foreach ((Guid ProductId, decimal QuantityKg) in items)
            {
                RoundProduct? roundProduct = round.RoundProducts.FirstOrDefault(rp => rp.ProductId == ProductId);
                if (roundProduct == null)
                {
                    continue;
                }

                OrderItem orderItem = new()
                {
                    Id = Guid.NewGuid(),
                    OrderId = order.Id,
                    ProductId = ProductId,
                    QuantityKg = QuantityKg,
                    EstimatedPricePerKg = roundProduct.GetEstimatedCustomerPrice(transportShareEstimate)
                };

                order.Items.Add(orderItem);
                totalEstimated += orderItem.QuantityKg * orderItem.EstimatedPricePerKg;
                roundProduct.AccumulatedQuantityKg += QuantityKg;
            }

            order.TotalEstimatedAmount = totalEstimated + order.DeliveryFee;
        }

        private static async Task UpdateRoundStatusIfTargetReached(Round round)
        {
            if (round.RoundProducts.All(static rp => rp.AccumulatedQuantityKg >= rp.TargetQuantityKg))
            {
                round.Status = RoundStatus.Locked;
            }
            await Task.CompletedTask; // Keep it async-ready
        }

        public async Task ConfirmOrderAsync(Guid orderId, string userId)
        {
            Order order = await _orderRepository.GetByIdAsync(orderId);
            if (order == null || order.UserId != userId)
            {
                throw new Exception("Order not found");
            }

            order.Status = OrderStatus.Confirmed;
            order.IsConfirmed = true;
            await _orderRepository.UpdateAsync(order);
        }

        public async Task RejectOrderAsync(Guid orderId, string userId)
        {
            Order order = await _orderRepository.GetByIdAsync(orderId);
            if (order == null || order.UserId != userId)
            {
                throw new Exception("Order not found");
            }

            order.Status = OrderStatus.Rejected;
            order.IsConfirmed = false;
            await _orderRepository.UpdateAsync(order);

            await AdjustRoundQuota(order, -1);
        }

        public async Task CancelOrderAsync(Guid orderId)
        {
            Order order = await _orderRepository.GetByIdAsync(orderId) ?? throw new Exception("Order not found");
            if (order.Status == OrderStatus.Cancelled)
            {
                return;
            }

            OrderStatus oldStatus = order.Status;
            order.Status = OrderStatus.Cancelled;
            await _orderRepository.UpdateAsync(order);

            if (oldStatus != OrderStatus.Rejected)
            {
                await AdjustRoundQuota(order, -1);
            }
        }

        public async Task UpdateStatusAsync(Guid orderId, OrderStatus status)
        {
            Order order = await _orderRepository.GetByIdAsync(orderId) ?? throw new KeyNotFoundException("Order not found");
            order.Status = status;
            await _orderRepository.UpdateAsync(order);
        }

        private async Task AdjustRoundQuota(Order order, int multiplier)
        {
            Round round = await _roundRepository.GetByIdAsync(order.RoundId);
            if (round == null)
            {
                return;
            }

            foreach (OrderItem item in order.Items)
            {
                RoundProduct? rp = round.RoundProducts.FirstOrDefault(p => p.ProductId == item.ProductId);
                if (rp != null)
                {
                    rp.AccumulatedQuantityKg += item.QuantityKg * multiplier;
                }
            }
            await _roundRepository.UpdateAsync(round);
        }
    }
}
